import {brotherhoodStatus} from './content-catalogue.mjs';
import {formatCampaignTime,starSymbols} from './campaign-progress.mjs';
export function createCampaignUI({document,data,getProgress,onScreen,onStart,onResume,onRetry,onCheckpoint,onReset,onNotice}){
 const $=id=>document.getElementById(id);let dayId=null,brotherhoodId=null,routeId=null,stepId=null;
 const total=(bucket,id)=>getProgress().totals[bucket][id];
 const requirement=item=>item.unlock?.completedRoute?`Completa ${data.routes.find(r=>r.id===item.unlock.completedRoute)?.name||'el recorrido anterior'} para desbloquearlo.`:`Necesitas ${item.unlock?.stars||0} ★ ${item.unlock?.scope==='day'?'de esta jornada':item.unlock?.scope==='brotherhood'?'de esta hermandad':'en total'}.`;
 const row=(title,detail,locked,click,media=null)=>{const button=document.createElement('button'),strong=document.createElement('strong'),text=document.createElement('span');button.className='day-card';button.dataset.status=locked?'locked':'available';strong.textContent=title;text.className='day-status';text.textContent=detail;button.append(strong,text);if(media){const cover=document.createElement(media.cover?'img':'span');cover.className='brotherhood-cover';if(media.cover){cover.src=media.cover;cover.alt='';}else cover.textContent='✦';const emblem=document.createElement(media.emblem?'img':'span');emblem.className='brotherhood-emblem';if(media.emblem){emblem.src=media.emblem;emblem.alt='Emblema';}else emblem.textContent='◇';button.append(cover,emblem);button.className+=' brotherhood-card';}button.setAttribute('aria-disabled',String(locked));button.onclick=locked?()=>onNotice(detail):click;return button;};
 function week(){const p=getProgress();$('campaign-total').textContent=`TOTAL ${p.totals.stars} / ${p.totals.max} ★`;
  $('day-list').replaceChildren(...data.days.map(d=>{const t=total('days',d.id),locked=!p.unlocked.days.includes(d.id);return row(d.name,`${t.stars} / ${t.max} ★ · ${locked?'🔒 '+requirement(d):t.max===0?'Próximamente':t.stars===t.max?'✓ Completado':'Disponible'}`,locked,()=>day(d.id));}));
 }
 function day(id){dayId=id;const d=data.days.find(d=>d.id===id),p=getProgress();if(!p.unlocked.days.includes(id)){onNotice(requirement(d));return;}const t=total('days',id);$('campaign-day-title').textContent=d.name;$('campaign-day-stars').textContent=`${t.stars} / ${t.max} ★`;
  const bs=data.brotherhoods.filter(b=>b.dayId===id);$('campaign-brotherhood-list').replaceChildren(...bs.map(b=>{const t=total('brotherhoods',b.id),locked=!p.unlocked.brotherhoods.includes(b.id);return row(b.name,`${t.stars} / ${t.max} ★ · ${locked?'🔒 '+requirement(b):`${brotherhoodStatus(data,p,b.id)} · ${t.max?Math.floor(t.stars/t.max*100):0}%`}`,locked,()=>brotherhood(b.id),b);}));$('campaign-day-note').textContent=bs.length?'Las hermandades se incorporarán paso a paso. Solo los pasos disponibles tienen recorridos jugables.':'Las hermandades de esta jornada llegarán próximamente.';onScreen('campaign-day-screen');
 }
 function routesFor(id,pas=null){return data.routes.filter(r=>r.brotherhoodId===id&&(!pas||r.stepRef===pas)).sort((a,b)=>(a.order||0)-(b.order||0));}
 function renderRoutes(id,pas,target){const p=getProgress(),routes=routesFor(id,pas);$(target).replaceChildren(...routes.map(r=>{const record=p.records[r.id],pending=r.playable===false,locked=pending||!p.unlocked.routes.includes(r.id);return row((r.archive?'PRUEBA ANTERIOR · ':`${r.order||1}. `)+r.name,pending?'PRÓXIMAMENTE':locked?'🔒 '+requirement(r):`${starSymbols(Math.max(record.stars,record.assistedStars))} · Mejor tiempo: ${formatCampaignTime(record.bestTimeMs)}${record.completedAssisted?' · Completado con checkpoint':''}`,locked,()=>route(r.id));}));if(!routes.length){const note=document.createElement('p');note.className='mode-note';note.textContent='Recorridos: próximamente';$(target).append(note);}}
 function brotherhood(id){brotherhoodId=id;stepId=null;const b=data.brotherhoods.find(b=>b.id===id);dayId=b.dayId;const p=getProgress(),t=total('brotherhoods',id);
  if(!p.unlocked.brotherhoods.includes(id)){onNotice(requirement(b));return;}
  $('campaign-brotherhood-title').textContent=b.name;$('campaign-brotherhood-stars').textContent=`${t.stars} / ${t.max} ★ · ${brotherhoodStatus(data,p,id)} · ${t.max?Math.floor(t.stars/t.max*100):0}%`;
  const steps=(data.steps||[]).filter(s=>s.brotherhoodId===id);$('campaign-step-list').replaceChildren(...steps.map(s=>row(s.type==='cristo'?'Cristo':'Cristo / Misterio',s.implemented?'DISPONIBLE':'PRÓXIMAMENTE',!s.implemented,()=>step(s.id),{cover:s.thumbnail||s.image})));
  $('campaign-pending-steps').textContent=steps.length?(b.pendingStepsLabel||'Otros pasos: próximamente'):'Pasos: próximamente';
  renderRoutes(id,null,'campaign-route-list');onScreen('campaign-brotherhood-screen');
 }
 function step(id){const s=data.steps.find(s=>s.id===id);if(!s?.implemented)return;stepId=id;brotherhoodId=s.brotherhoodId;dayId=data.brotherhoods.find(b=>b.id===brotherhoodId).dayId;$('campaign-step-title').textContent=s.name;$('campaign-step-kind').textContent=s.type==='cristo'?'PASO DE CRISTO':'PASO DE CRISTO / MISTERIO';renderRoutes(brotherhoodId,id,'campaign-step-routes');onScreen('campaign-step-screen');}
 function route(id){routeId=id;const r=data.routes.find(r=>r.id===id),p=getProgress();if(!p.unlocked.routes.includes(id)){onNotice(requirement(r));return;}stepId=r.stepRef||null;brotherhoodId=r.brotherhoodId;dayId=data.brotherhoods.find(b=>b.id===brotherhoodId).dayId;const record=p.records[id];$('campaign-route-title').textContent=r.name;$('campaign-route-brotherhood').textContent=data.brotherhoods.find(b=>b.id===brotherhoodId).name;$('campaign-start').textContent='COMENZAR';$('campaign-targets').textContent=`★★★ ≤ ${formatCampaignTime(r.threeStars*1000)}\n★★☆ ≤ ${formatCampaignTime(r.twoStars*1000)}\n★☆☆ Completar${r.provisionalTimes?'\nTiempos provisionales de prueba':''}`;
  $('campaign-best').textContent=`MEJOR TIEMPO: ${formatCampaignTime(record.bestTimeMs)}\nMEJOR RESULTADO: ${starSymbols(Math.max(record.stars,record.assistedStars))}`;
  $('campaign-route-note').textContent=r.instructions|| (r.mapKey==='SalidaPureza'?'Paso: Cristo / Misterio. Salida manual por la puerta y giro hacia el Altozano. Un punto de control antes de la curva, señalado en azul. Llegada dorada al Altozano: arriar dentro del recuadro. Reanudar desde el checkpoint recupera el tiempo que llevabas al cruzarlo; puedes conseguir estrellas y récord según el tiempo final. Puedes arriar para descansar; el cronómetro sigue contando.':`Paso: ${data.steps?.find(s=>s.id===r.stepRef)?.name||'Paso existente'}. ${r.checkpoints.points.length} checkpoint(s) de reanudación. Reanudar recupera el tiempo guardado; las estrellas y el récord dependen del tiempo final.`);
  const active=p.active;$('campaign-resume').hidden=active?.routeId!==id||active.phase==='failed';$('campaign-resume-checkpoint').hidden=active?.routeId!==id||!active.checkpoint;$('campaign-resume-checkpoint').textContent=r.mapKey==='RegresoArenal'?'REINICIAR DESDE BARATILLO':'REANUDAR DESDE CHECKPOINT';$('campaign-start').onclick=()=>onStart(id);$('campaign-resume').onclick=()=>onResume(id,false);$('campaign-resume-checkpoint').onclick=()=>onResume(id,true);onScreen('campaign-route-screen');
 }
 function result(r,attempt,e,outcome){routeId=r.id;stepId=r.stepRef||null;brotherhoodId=r.brotherhoodId;dayId=data.brotherhoods.find(b=>b.id===brotherhoodId).dayId;const won=e.type==='won';$('campaign-result-title').textContent=won?'RECORRIDO COMPLETADO':'RECORRIDO FALLIDO';
  $('campaign-result-message').textContent=won?(outcome.assisted?'Has completado el recorrido utilizando un checkpoint.':'Has completado el recorrido sin reinicios.'):(e.reason||'Has golpeado el paso.');
  const record=getProgress().records[r.id];$('campaign-result-details').textContent=`Tiempo: ${formatCampaignTime(attempt.clock.elapsedMs)}\nMejor tiempo: ${formatCampaignTime(record.bestTimeMs)}\n${won?'Resultado actual: '+starSymbols(outcome.currentStars)+'\n':''}Mejor resultado: ${starSymbols(Math.max(record.stars,record.assistedStars))}${outcome?.newRecord?'\nNUEVO RÉCORD':''}${won&&r.presentations?'\nPRESENTACIÓN BARATILLO: COMPLETADA':''}${won&&outcome.assisted&&r.checkpoints.policy==='cleanRecord'?'\nCon checkpoint: máximo dos estrellas · Sin récord general':''}`;
  $('campaign-repeat').textContent=won?'REPETIR':'REINTENTAR';$('campaign-result-back').textContent=won?'CONTINUAR':'VOLVER';$('campaign-checkpoint').hidden=won||!attempt.checkpoint;$('campaign-checkpoint').textContent=r.mapKey==='RegresoArenal'?'REINICIAR DESDE BARATILLO':'REANUDAR DESDE CHECKPOINT';onScreen('campaign-result-screen');
 }
 $('campaign-day-back').onclick=()=>{week();onScreen('week-screen');};$('campaign-brotherhood-back').onclick=()=>day(dayId);$('campaign-step-back').onclick=()=>brotherhood(brotherhoodId);$('campaign-route-back').onclick=()=>stepId?step(stepId):brotherhood(brotherhoodId);
 $('campaign-repeat').onclick=onRetry;$('campaign-checkpoint').onclick=onCheckpoint;$('campaign-result-back').onclick=()=>brotherhood(brotherhoodId);
 $('reset-campaign').onclick=()=>onScreen('campaign-reset-screen');$('cancel-reset-campaign').onclick=()=>onScreen('settings-screen');$('confirm-reset-campaign').onclick=()=>{onReset();onScreen('settings-screen');onNotice('El progreso de Semana Santa se ha restablecido.');};
 return {week,day,brotherhood,step,route,result,currentRoute:()=>routeId};
}
